name: ğŸš€ GitHub Actions
on:
  # developãƒ–ãƒ©ãƒ³ãƒã«pushã•ã‚ŒãŸæ™‚
  push:
    branches:
      - develop
  # pull requestã‚’ä½œæˆã—ãŸæ™‚
  pull_request: {}

jobs:
  typecheck:
    name: TypeScript
    # ubuntuã®æœ€æ–°ãƒãƒ¼ã‚¸ãƒ§ãƒ³ã§å®Ÿè¡Œ
    runs-on: ubuntu-latest
    steps:
      # - name: Cancel Previous Runs
      #   uses: styfle/cancel-workflow-action@0.12.0

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # package-lock.jsonã‹ã‚‰ãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ã®ãƒãƒ¼ã‚¸ãƒ§ãƒ³ã‚’ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«
      - name: Install packages
        run: npm ci

      - name: Run TypeScript Check
        run: npm run typecheck

  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # - name: Cancel Previous Runs
      #   uses: styfle/cancel-workflow-action@0.12.0

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: npm ci

      - name: Run Lint
        run: npm run lint

  Prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      # - name: Cancel Previous Runs
      #   uses: styfle/cancel-workflow-action@0.12.0

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: npm ci

      - name: Run Prettier
        run: npm run format

  vitest:
    name: Vitest
    runs-on: ubuntu-latest
    steps:
      # - name: Cancel Previous Runs
      #   uses: styfle/cancel-workflow-action@0.12.0

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: npm ci

      - name: Run vitest
        run: npm run test
